# Generated by Django 3.2.5 on 2021-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
    ]
