# Generated by Django 3.2.5 on 2021-07-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_usercategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User Category'},
        ),
        migrations.AddConstraint(
            model_name='usercategory',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique user category'),
        ),
    ]
