# Generated by Django 3.2.5 on 2021-07-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20210718_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.category')),
            ],
            options={
                'verbose_name': 'Activity Category',
            },
        ),
        migrations.AddConstraint(
            model_name='activitycategory',
            constraint=models.UniqueConstraint(fields=('activity', 'category'), name='unique activity category'),
        ),
    ]
